package exporter_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/user/envlens/internal/exporter"
)

var sampleEnv = map[string]string{
	"APP_ENV":  "production",
	"DB_URL":   "postgres://localhost/mydb",
	"SECRET":   "p@ss word",
	"PLAIN_KEY": "simplevalue",
}

func TestExport_DotenvFormat(t *testing.T) {
	var buf bytes.Buffer
	opts := exporter.DefaultOptions()
	if err := exporter.Export(&buf, sampleEnv, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "APP_ENV=production") {
		t.Errorf("expected plain assignment, got:\n%s", out)
	}
	if !strings.Contains(out, "SECRET=") {
		t.Errorf("expected SECRET in output, got:\n%s", out)
	}
}

func TestExport_ShellFormat(t *testing.T) {
	var buf bytes.Buffer
	opts := exporter.Options{Format: exporter.FormatShell, Sorted: true}
	if err := exporter.Export(&buf, map[string]string{"FOO": "bar"}, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(buf.String(), `FOO="bar"`) {
		t.Errorf("expected quoted shell assignment, got: %s", buf.String())
	}
}

func TestExport_ExportFormat(t *testing.T) {
	var buf bytes.Buffer
	opts := exporter.Options{Format: exporter.FormatExport, Sorted: true}
	if err := exporter.Export(&buf, map[string]string{"BAR": "baz"}, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(buf.String(), "export ") {
		t.Errorf("expected export prefix, got: %s", buf.String())
	}
}

func TestExport_WithComment(t *testing.T) {
	var buf bytes.Buffer
	opts := exporter.Options{Format: exporter.FormatDotenv, Sorted: true, Comment: "generated by envlens"}
	if err := exporter.Export(&buf, map[string]string{"X": "1"}, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(buf.String(), "# generated by envlens") {
		t.Errorf("expected comment header, got: %s", buf.String())
	}
}

func TestExportToFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.env")
	opts := exporter.DefaultOptions()
	if err := exporter.ExportToFile(path, sampleEnv, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	if !strings.Contains(string(data), "APP_ENV=production") {
		t.Errorf("expected APP_ENV in file, got:\n%s", string(data))
	}
}

func TestExport_Sorted(t *testing.T) {
	var buf bytes.Buffer
	opts := exporter.Options{Format: exporter.FormatDotenv, Sorted: true}
	env := map[string]string{"Z_KEY": "z", "A_KEY": "a", "M_KEY": "m"}
	if err := exporter.Export(&buf, env, opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	lines := strings.Split(strings.TrimSpace(buf.String()), "\n")
	if !strings.HasPrefix(lines[0], "A_KEY") {
		t.Errorf("expected sorted output, first line: %s", lines[0])
	}
}
